name: bigpanda_interview
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - ./tmp/target
  - ./tmp/dbt_packages
  - ./dbt_packages
  - ./dbt_modules

#Defining future schema if any dbt seeds are added
seeds:
  +schema: dbt_seeds